INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ('004', '004', 'AFG',  'AF',  'Afganistán',  'Afganistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '02','02','248',  'ALA',  'AX',  'Åland',  'Åland');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '03','03', '008',  'ALB',  'AL',  'Albania',  'Albania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '276','276',  'DEU',  'DE',  'Alemania',  'Alemania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '020','020',  'AND',  'AD',  'Andorra',  'Andorra');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '024','024',  'AGO',  'AO',  'Angola',  'Angola');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '660','660',  'AIA',  'AI',  'Anguila',  'Anguila');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '010','010',  'ATA',  'AQ',  'Antártida',  'Antártida');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '028','028',  'ATG',  'AG',  'Antigua y Barbuda',  'Antigua y Barbuda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '530','530',  'ANT',  'AN',  'Antillas Neerlandesas',  'Antillas Neerlandesas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '682','682',  'SAU',  'SA',  'Arabia Saudita',  'Arabia Saudita');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '012','012',  'DZA',  'DZ',  'Argelia',  'Argelia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '032','032',  'ARG',  'AR',  'Argentina',  'Argentina');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '051','051',  'ARM',  'AM',  'Armenia',  'Armenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '533','533',  'ABW',  'AW',  'Aruba',  'Aruba');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '036','036',  'AUS',  'AU',  'Australia',  'Australia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '040','040',  'AUT',  'AT',  'Austria',  'Austria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '031','031',  'AZE',  'AZ',  'Azerbaiyán',  'Azerbaiyán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '044','044',  'BHS',  'BS',  'Bahamas',  'Bahamas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '048','048',  'BHR',  'BH',  'Bahréin',  'Bahréin');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '050','050',  'BGD',  'BD',  'Bangladesh',  'Bangladesh');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '052','052',  'BRB',  'BB',  'Barbados',  'Barbados');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '112','112',  'BLR',  'BY',  'Bielorrusia',  'Bielorrusia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '056','056',  'BEL',  'BE',  'Bélgica',  'Bélgica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '084','084',  'BLZ',  'BZ',  'Belice',  'Belice');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '204','204',  'BEN',  'BJ',  'Benín',  'Benín');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '060','060',  'BMU',  'BM',  'Bermudas',  'Bermudas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '064','064',  'BTN',  'BT',  'Bután',  'Bután');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '068','068',  'BOL',  'BO',  'Bolivia',  'Bolivia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '070','070',  'BIH',  'BA',  'Bosnia y Herzegovina',  'Bosnia y Herzegovina');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '072','072',  'BWA',  'BW',  'Botsuana',  'Botsuana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '074','074',  'BVT',  'BV',  'Isla Bouvet',  'Isla Bouvet');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '076','076',  'BRA',  'BR',  'Brasil',  'Brasil');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '096','096',  'BRN',  'BN',  'Brunéi',  'Brunéi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '100','100',  'BGR',  'BG',  'Bulgaria',  'Bulgaria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '854','854',  'BFA',  'BF',  'Burkina Faso',  'Burkina Faso');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '108','108',  'BDI',  'BI',  'Burundi',  'Burundi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '132','132',  'CPV',  'CV',  'Cabo Verde',  'Cabo Verde');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '136','136',  'CYM',  'KY',  'Islas Caimán',  'Islas Caimán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '116','116',  'KHM',  'KH',  'Camboya',  'Camboya');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '120','120',  'CMR',  'CM',  'Camerún',  'Camerún');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '124','124',  'CAN',  'CA',  'Canadá',  'Canadá');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '140','140',  'CAF',  'CF',  'República Centroafricana',  'República Centroafricana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '148','148',  'TCD',  'TD',  'Chad',  'Chad');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '203','203',  'CZE',  'CZ',  'República Checa',  'República Checa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '152','152',  'CHL',  'CL',  'Chile',  'Chileno(a)');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '156','156',  'CHN',  'CN',  'China',  'China');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '196','196',  'CYP',  'CY',  'Chipre',  'Chipre');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '166','166',  'CCK',  'CC',  'Islas Cocos',  'Islas Cocos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '170','170',  'COL',  'CO',  'Colombia',  'Colombia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '174','174',  'COM',  'KM',  'Comoras',  'Comoras');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '178','178',  'COG',  'CG',  'República del Congo',  'República del Congo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '180','180',  'COD',  'CD',  'República Democrática del Congo',  'República Democrática del Congo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '184','184',  'COK',  'CK',  'Islas Cook',  'Islas Cook');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '408','408',  'PRK',  'KP',  'Corea del Norte',  'Corea del Norte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '410','410',  'KOR',  'KR',  'Corea del Sur',  'Corea del Sur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '384','384',  'CIV',  'CI',  'Costa de Marfil',  'Costa de Marfil');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '188','188',  'CRI',  'CR',  'Costa Rica',  'Costa Rica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '191','191',  'HRV',  'HR',  'Croacia',  'Croacia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '192','192',  'CUB',  'CU',  'Cuba',  'Cuba');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '208','208',  'DNK',  'DK',  'Dinamarca',  'Dinamarca');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '212','212',  'DMA',  'DM',  'Dominica',  'Dominica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '214','214',  'DOM',  'DO',  'República Dominicana',  'República Dominicana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '218','218',  'ECU',  'EC',  'Ecuador',  'Ecuador');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '818','818',  'EGY',  'EG',  'Egipto',  'Egipto');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '222','222',  'SLV',  'SV',  'El Salvador',  'El Salvador');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '784','784',  'ARE',  'AE',  'Emiratos Árabes Unidos',  'Emiratos Árabes Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '232','232',  'ERI',  'ER',  'Eritrea',  'Eritrea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '703','703',  'SVK',  'SK',  'Eslovaquia',  'Eslovaquia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '705','705',  'SVN',  'SI',  'Eslovenia',  'Eslovenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '724','724',  'ESP',  'ES',  'España',  'España');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '840','840',  'USA',  'US',  'Estados Unidos',  'Estados Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '581','581',  'UMI',  'UM',  'Islas ultramarinas de EstadosUnidos',  'Islas ultramarinas de Estados Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '233','233',  'EST',  'EE',  'Estonia',  'Estonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '231','231',  'ETH',  'ET',  'Etiopía',  'Etiopía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '234','234',  'FRO',  'FO',  'Islas Feroe',  'Islas Feroe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '608','608',  'PHL',  'PH',  'Filipinas',  'Filipinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '246','246',  'FIN',  'FI',  'Finlandia',  'Finlandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '242','242',  'FJI',  'FJ',  'Fiyi',  'Fiyi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '250','250',  'FRA',  'FR',  'Francia',  'Francia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '266','266',  'GAB',  'GA',  'Gabón',  'Gabón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '270','270',  'GMB',  'GM',  'Gambia',  'Gambia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '268','268',  'GEO',  'GE',  'Georgia',  'Georgia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '239','239',  'SGS',  'GS',  'Islas Georgias del SurySandwichdelSur',  'Islas Georgias del SurySandwichdelSur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '288','288',  'GHA',  'GH',  'Ghana',  'Ghana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '292','292',  'GIB',  'GI',  'Gibraltar',  'Gibraltar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '308','308',  'GRD',  'GD',  'Granada',  'Granada');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '300','300',  'GRC',  'GR',  'Grecia',  'Grecia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '304','304',  'GRL',  'GL',  'Groenlandia',  'Groenlandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '312','312',  'GLP',  'GP',  'Guadalupe',  'Guadalupe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '316','316',  'GUM',  'GU',  'Guam',  'Guam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '320','320',  'GTM',  'GT',  'Guatemala',  'Guatemala');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '254','254',  'GUF',  'GF',  'Guayana Francesa',  'Guayana Francesa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '831','831',  'GGY',  'GG',  'Guernsey',  'Guernsey');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '324','324',  'GIN',  'GN',  'Guinea',  'Guinea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '226','226',  'GNQ',  'GQ',  'Guinea Ecuatorial',  'Guinea Ecuatorial');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '624','624',  'GNB',  'GW',  'Guinea-Bissau',  'Guinea-Bissau');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '328','328',  'GUY',  'GY',  'Guyana',  'Guyana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '332','332',  'HTI',  'HT',  'Haití',  'Haití');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '334','334',  'HMD',  'HM',  'Islas Heard y McDonald',  'Islas Heard y McDonald');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '340','340',  'HND',  'HN',  'Honduras',  'Honduras');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '344','344',  'HKG',  'HK',  'Hong Kong',  'Hong Kong');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '348','348',  'HUN',  'HU',  'Hungría',  'Hungría');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '356','356',  'IND',  'IN',  'India',  'India');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '360','360',  'IDN',  'ID',  'Indonesia',  'Indonesia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '364','364',  'IRN',  'IR',  'Irán',  'Irán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '368','368',  'IRQ',  'IQ',  'Iraq',  'Iraq');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '372','372',  'IRL',  'IE',  'Irlanda',  'Irlanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '352','352',  'ISL',  'IS',  'Islandia',  'Islandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '376','376',  'ISR',  'IL',  'Israel',  'Israel');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '380','380',  'ITA',  'IT',  'Italia',  'Italia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '388','388',  'JAM',  'JM',  'Jamaica',  'Jamaica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '392','392',  'JPN',  'JP',  'Japón',  'Japón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '832','832',  'JEY',  'JE',  'Jersey',  'Jersey');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '400','400',  'JOR',  'JO',  'Jordania',  'Jordania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '398','398',  'KAZ',  'KZ',  'Kazajistán',  'Kazajistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '404','404',  'KEN',  'KE',  'Kenia',  'Kenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '417','417',  'KGZ',  'KG',  'Kirguistán',  'Kirguistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '296','296',  'KIR',  'KI',  'Kiribati',  'Kiribati');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '414','414',  'KWT',  'KW',  'Kuwait',  'Kuwait');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '418','418',  'LAO',  'LA',  'Laos',  'Laos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '426','426',  'LSO',  'LS',  'Lesoto',  'Lesoto');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '428','428',  'LVA',  'LV',  'Letonia',  'Letonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '422','422',  'LBN',  'LB',  'Líbano',  'Líbano');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '430','430',  'LBR',  'LR',  'Liberia',  'Liberia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '434','434',  'LBY',  'LY',  'Libia',  'Libia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '438','438',  'LIE',  'LI',  'Liechtenstein',  'Liechtenstein');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '440','440',  'LTU',  'LT',  'Lituania',  'Lituania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '442','442',  'LUX',  'LU',  'Luxemburgo',  'Luxemburgo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '446','446',  'MAC',  'MO',  'Macao',  'Macao');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '807','807',  'MKD',  'MK',  'ARY Macedonia',  'ARY Macedonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '450','450',  'MDG',  'MG',  'Madagascar',  'Madagascar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '458','458',  'MYS',  'MY',  'Malasia',  'Malasia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '454','454',  'MWI',  'MW',  'Malawi',  'Malawi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '462','462',  'MDV',  'MV',  'Maldivas',  'Maldivas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '466','466',  'MLI',  'ML',  'Malí',  'Malí');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '470','470',  'MLT',  'MT',  'Malta',  'Malta');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '238','238',  'FLK',  'FK',  'Islas Malvinas',  'Islas Malvinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '833','833',  'IMN',  'IM',  'Isla de Man',  'Isla de Man');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '580','580',  'MNP',  'MP',  'Islas Marianas del Norte',  'Islas Marianas del Norte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '504','504',  'MAR',  'MA',  'Marruecos',  'Marruecos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '584','584',  'MHL',  'MH',  'Islas Marshall',  'Islas Marshall');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '474','474',  'MTQ',  'MQ',  'Martinica',  'Martinica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '480','480',  'MUS',  'MU',  'Mauricio',  'Mauricio');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '478','478',  'MRT',  'MR',  'Mauritania',  'Mauritania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '175','175',  'MYT',  'YT',  'Mayotte',  'Mayotte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '484','484',  'MEX',  'MX',  'México',  'México');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '583','583',  'FSM',  'FM',  'Micronesia',  'Micronesia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '498','498',  'MDA',  'MD',  'Moldavia',  'Moldavia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '492','492',  'MCO',  'MC',  'Mónaco',  'Mónaco');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '496','496',  'MNG',  'MN',  'Mongolia',  'Mongolia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '499','499',  'MNE',  'ME',  'Montenegro',  'Montenegro');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '500','500',  'MSR',  'MS',  'Montserrat',  'Montserrat');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '508','508',  'MOZ',  'MZ',  'Mozambique',  'Mozambique');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '104','104',  'MMR',  'MM',  'Birmania',  'Birmania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '516','516',  'NAM',  'NA',  'Namibia',  'Namibia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '520','520',  'NRU',  'NR',  'Nauru',  'Nauru');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '162','162',  'CXR',  'CX',  'Isla de Navidad',  'Isla de Navidad');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '524','524',  'NPL',  'NP',  'Nepal',  'Nepal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '558','558',  'NIC',  'NI',  'Nicaragua',  'Nicaragua');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '562','562',  'NER',  'NE',  'Níger',  'Níger');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '566','566',  'NGA',  'NG',  'Nigeria',  'Nigeria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '570','570',  'NIU',  'NU',  'Niue',  'Niue');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '574','574',  'NFK',  'NF',  'Norfolk',  'Norfolk');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '578','578',  'NOR',  'NO',  'Noruega',  'Noruega');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '540','540',  'NCL',  'NC',  'Nueva Caledonia',  'Nueva Caledonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '554','554',  'NZL',  'NZ',  'Nueva Zelanda',  'Nueva Zelanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '512','512',  'OMN',  'OM',  'Omán',  'Omán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '528','528',  'NLD',  'NL',  'Países Bajos',  'Países Bajos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '586','586',  'PAK',  'PK',  'Pakistán',  'Pakistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '585','585',  'PLW',  'PW',  'Palaos',  'Palaos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '275','275',  'PSE',  'PS',  'Territorios palestinos',  'Territorios palestinos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '591','591',  'PAN',  'PA',  'Panamá',  'Panamá');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '598','598',  'PNG',  'PG',  'Papúa Nueva Guinea',  'Papúa Nueva Guinea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '600','600',  'PRY',  'PY',  'Paraguay',  'Paraguay');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '604','604',  'PER',  'PE',  'Perú',  'Perú');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '612','612',  'PCN',  'PN',  'Islas Pitcairn',  'Islas Pitcairn');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '258','258',  'PYF',  'PF',  'Polinesia Francesa',  'Polinesia Francesa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '616','616',  'POL',  'PL',  'Polonia',  'Polonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '620','620',  'PRT',  'PT',  'Portugal',  'Portugal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '630','630',  'PRI',  'PR',  'Puerto Rico',  'Puerto Rico');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '634','634',  'QAT',  'QA',  'Qatar',  'Qatar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '826','826',  'GBR',  'GB',  'Reino Unido',  'Reino Unido');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '638','638',  'REU',  'RE',  'Reunión',  'Reunión');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '646','646',  'RWA',  'RW',  'Ruanda',  'Ruanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '642','642',  'ROU',  'RO',  'Rumania',  'Rumania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '643','643',  'RUS',  'RU',  'Rusia',  'Rusia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '732','732',  'ESH',  'EH',  'Sahara Occidental',  'Sahara Occidental');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '090','090',  'SLB',  'SB',  'Islas Salomón',  'Islas Salomón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '882','882',  'WSM',  'WS',  'Samoa',  'Samoa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '016','016',  'ASM',  'AS',  'Americana Samoa Americana',  'Americana Samoa Americana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '659','659',  'KNA',  'KN',  'San Cristóbal y Nieves',  'San Cristóbal y Nieves');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '674','674',  'SMR',  'SM',  'San Marino',  'San Marino');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '666','666',  'SPM',  'PM',  'San Pedro y Miquelón',  'San Pedro y Miquelón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '670','670',  'VCT',  'VC',  'San Vicente y lasGranadinas',  'San Vicente y lasGranadinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '654','654',  'SHN',  'SH',  'Santa Helena',  'Santa Helena');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '662','662',  'LCA',  'LC',  'Santa Lucía',  'Santa Lucía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '678','678',  'STP',  'ST',  'Santo Tomé y Príncipe',  'Santo Tomé y Príncipe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '686','686',  'SEN',  'SN',  'Senegal',  'Senegal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '688','688',  'SRB',  'RS',  'Serbia',  'Serbia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '690','690',  'SYC',  'SC',  'Seychelles',  'Seychelles');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '694','694',  'SLE',  'SL',  'Sierra Leona',  'Sierra Leona');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '702','702',  'SGP',  'SG',  'Singapur',  'Singapur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '760','760',  'SYR',  'SY',  'Siria',  'Siria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '706','706',  'SOM',  'SO',  'Somalia',  'Somalia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '144','144',  'LKA',  'LK',  'Sri Lanka',  'Sri Lanka');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '748','748',  'SWZ',  'SZ',  'Suazilandia',  'Suazilandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '710','710',  'ZAF',  'ZA',  'Sudáfrica',  'Sudáfrica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '736','736',  'SDN',  'SD',  'Sudán',  'Sudán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '752','752',  'SWE',  'SE',  'Suecia',  'Suecia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '756','756',  'CHE',  'CH',  'Suiza',  'Suiza');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '740','740',  'SUR',  'SR',  'Surinam',  'Surinam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '744','744',  'SJM',  'SJ',  'Svalbard y Jan Mayen',  'Svalbard y Jan Mayen');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '764','764',  'THA',  'TH',  'Tailandia',  'Tailandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '158','158',  'TWN',  'TW',  'República de China',  'República de China');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '834','834',  'TZA',  'TZ',  'Tanzania',  'Tanzania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '762','762',  'TJK',  'TJ',  'Tayikistán',  'Tayikistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '086','086',  'IOT',  'IO',  'Territorio Británico del OcéanoÍndico',  'Territorio Británico del Océano Índico');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '260','260',  'ATF',  'TF',  'Territorios Australes Franceses',  'Territorios Australes Franceses');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '626','626',  'TLS',  'TL',  'Timor Oriental',  'Timor Oriental');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '768','768',  'TGO',  'TG',  'Togo',  'Togo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '772','772',  'TKL',  'TK',  'Tokelau',  'Tokelau');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '776','776',  'TON',  'TO',  'Tonga',  'Tonga');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '780','780',  'TTO',  'TT',  'Trinidad y Tobago',  'Trinidad y Tobago');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '788','788',  'TUN',  'TN',  'Túnez',  'Túnez');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '796','796',  'TCA',  'TC',  'Islas Turcas y Caicos',  'Islas Turcas y Caicos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '795','795',  'TKM',  'TM',  'Turkmenistán',  'Turkmenistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '792','792',  'TUR',  'TR',  'Turquía',  'Turquía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '798','798',  'TUV',  'TV',  'Tuvalu',  'Tuvalu');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '804','804',  'UKR',  'UA',  'Ucrania',  'Ucrania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '800','800',  'UGA',  'UG',  'Uganda',  'Uganda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '858','858',  'URY',  'UY',  'Uruguay',  'Uruguay');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '860','860',  'UZB',  'UZ',  'Uzbekistán',  'Uzbekistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '548','548',  'VUT',  'VU',  'Vanuatu',  'Vanuatu');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '336','336',  'VAT',  'VA',  'Ciudad del Vaticano',  'Ciudad del Vaticano');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '862','862',  'VEN',  'VE',  'Venezuela',  'Venezuela');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '704','704',  'VNM',  'VN',  'Vietnam',  'Vietnam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '092','092',  'VGB',  'VG',  'Islas Vírgenes Británicas',  'Islas Vírgenes Británicas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '850','850',  'VIR',  'VI',  'Islas Vírgenes Estadounidenses',  'Islas Vírgenes Estadounidenses');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '876','876',  'WLF',  'WF',  'Wallis y Futuna',  'Wallis y Futuna');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '887','887',  'YEM',  'YE',  'Yemen',  'Yemen');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '262','262',  'DJI',  'DJ',  'Yibuti',  'Yibuti');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '894','894',  'ZMB',  'ZM',  'Zambia',  'Zambia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '716','716',  'ZWE',  'ZW',  'Zimbabue',  'Zimbabue');