INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ('004', '004', 'AFG',  'AF',  'Afganistán',  'Afganistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '02','248',  'ALA',  'AX',  'Aland',  'Aland');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '03','03', '008',  'ALB',  'AL',  'Albania',  'Albania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '276','276',  'DEU',  'DE',  'Alemania',  'Alemania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '020','020',  'AND',  'AD',  'Andorra',  'Andorra');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '024','024',  'AGO',  'AO',  'Angola',  'Angola');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '660','660',  'AIA',  'AI',  'Anguila',  'Anguila');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '010','010',  'ATA',  'AQ',  'Antártida',  'Antártida');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '028','028',  'ATG',  'AG',  'Antigua y Barbuda',  'Antigua y Barbuda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '530','530',  'ANT',  'AN',  'Antillas Neerlandesas',  'Antillas Neerlandesas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '682','682',  'SAU',  'SA',  'Arabia Saudita',  'Arabia Saudita');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '012','012',  'DZA',  'DZ',  'Argelia',  'Argelia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '032','032',  'ARG',  'AR',  'Argentina',  'Argentina');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '051','051',  'ARM',  'AM',  'Armenia',  'Armenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '533','533',  'ABW',  'AW',  'Aruba',  'Aruba');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '036','036',  'AUS',  'AU',  'Australia',  'Australia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '040','040',  'AUT',  'AT',  'Austria',  'Austria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '031','031',  'AZE',  'AZ',  'Azerbaiyán',  'Azerbaiyán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '044','044',  'BHS',  'BS',  'Bahamas',  'Bahamas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '048','048',  'BHR',  'BH',  'Bahréin',  'Bahréin');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '050','050',  'BGD',  'BD',  'Bangladesh',  'Bangladesh');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '052','052',  'BRB',  'BB',  'Barbados',  'Barbados');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '112','112',  'BLR',  'BY',  'Bielorrusia',  'Bielorrusia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '056','056',  'BEL',  'BE',  'Bélgica',  'Bélgica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '084','084',  'BLZ',  'BZ',  'Belice',  'Belice');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '204','204',  'BEN',  'BJ',  'Benín',  'Benín');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '060','060',  'BMU',  'BM',  'Bermudas',  'Bermudas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '064','064',  'BTN',  'BT',  'Bután',  'Bután');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '068','068',  'BOL',  'BO',  'Bolivia',  'Bolivia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '070','070',  'BIH',  'BA',  'Bosnia y Herzegovina',  'Bosnia y Herzegovina');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '072','072',  'BWA',  'BW',  'Botsuana',  'Botsuana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '074','074',  'BVT',  'BV',  'Isla Bouvet',  'Isla Bouvet');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '076','076',  'BRA',  'BR',  'Brasil',  'Brasil');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '096','096',  'BRN',  'BN',  'Brunéi',  'Brunéi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '100','100',  'BGR',  'BG',  'Bulgaria',  'Bulgaria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '854','854',  'BFA',  'BF',  'Burkina Faso',  'Burkina Faso');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '108','108',  'BDI',  'BI',  'Burundi',  'Burundi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '132','132',  'CPV',  'CV',  'Cabo Verde',  'Cabo Verde');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '136','136',  'CYM',  'KY',  'Islas Caimán',  'Islas Caimán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '116','116',  'KHM',  'KH',  'Camboya',  'Camboya');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '120','120',  'CMR',  'CM',  'Camerún',  'Camerún');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '124','124',  'CAN',  'CA',  'Canadá',  'Canadá');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '140','140',  'CAF',  'CF',  'República Centroafricana',  'República Centroafricana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '148','148',  'TCD',  'TD',  'Chad',  'Chad');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '203','203',  'CZE',  'CZ',  'República Checa',  'República Checa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '152','152',  'CHL',  'CL',  'Chile',  'Chileno(a)');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '156','156',  'CHN',  'CN',  'China',  'China');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '196','196',  'CYP',  'CY',  'Chipre',  'Chipre');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '166','166',  'CCK',  'CC',  'Islas Cocos',  'Islas Cocos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '170','170',  'COL',  'CO',  'Colombia',  'Colombia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '174','174',  'COM',  'KM',  'Comoras',  'Comoras');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '178','178',  'COG',  'CG',  'República del Congo',  'República del Congo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '180','180',  'COD',  'CD',  'República Democrática del Congo',  'República Democrática del Congo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '184','184',  'COK',  'CK',  'Islas Cook',  'Islas Cook');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '408','408',  'PRK',  'KP',  'Corea del Norte',  'Corea del Norte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '410','410',  'KOR',  'KR',  'Corea del Sur',  'Corea del Sur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '384','384',  'CIV',  'CI',  'Costa de Marfil',  'Costa de Marfil');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '188','188',  'CRI',  'CR',  'Costa Rica',  'Costa Rica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '191','191',  'HRV',  'HR',  'Croacia',  'Croacia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '192','192',  'CUB',  'CU',  'Cuba',  'Cuba');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '208','208',  'DNK',  'DK',  'Dinamarca',  'Dinamarca');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '212','212',  'DMA',  'DM',  'Dominica',  'Dominica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '214','214',  'DOM',  'DO',  'República Dominicana',  'República Dominicana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '218','218',  'ECU',  'EC',  'Ecuador',  'Ecuador');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '818','818',  'EGY',  'EG',  'Egipto',  'Egipto');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '222','222',  'SLV',  'SV',  'El Salvador',  'El Salvador');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '784','784',  'ARE',  'AE',  'Emiratos Árabes Unidos',  'Emiratos Árabes Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '232','232',  'ERI',  'ER',  'Eritrea',  'Eritrea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '703','703',  'SVK',  'SK',  'Eslovaquia',  'Eslovaquia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '705','705',  'SVN',  'SI',  'Eslovenia',  'Eslovenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '724','724',  'ESP',  'ES',  'España',  'España');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '840','840',  'USA',  'US',  'Estados Unidos',  'Estados Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '581','581',  'UMI',  'UM',  'Islas ultramarinas de EstadosUnidos',  'Islas ultramarinas de Estados Unidos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '233','233',  'EST',  'EE',  'Estonia',  'Estonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '231','231',  'ETH',  'ET',  'Etiopía',  'Etiopía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '234','234',  'FRO',  'FO',  'Islas Feroe',  'Islas Feroe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '608','608',  'PHL',  'PH',  'Filipinas',  'Filipinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '246','246',  'FIN',  'FI',  'Finlandia',  'Finlandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '242','242',  'FJI',  'FJ',  'Fiyi',  'Fiyi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '250','250',  'FRA',  'FR',  'Francia',  'Francia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '266','266',  'GAB',  'GA',  'Gabón',  'Gabón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '270','270',  'GMB',  'GM',  'Gambia',  'Gambia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '268','268',  'GEO',  'GE',  'Georgia',  'Georgia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '239','239',  'SGS',  'GS',  'Islas Georgias del SurySandwichdelSur',  'Islas Georgias del SurySandwichdelSur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '288','288',  'GHA',  'GH',  'Ghana',  'Ghana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '292','292',  'GIB',  'GI',  'Gibraltar',  'Gibraltar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '308','308',  'GRD',  'GD',  'Granada',  'Granada');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '300','300',  'GRC',  'GR',  'Grecia',  'Grecia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '304','304',  'GRL',  'GL',  'Groenlandia',  'Groenlandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '312','312',  'GLP',  'GP',  'Guadalupe',  'Guadalupe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '316','316',  'GUM',  'GU',  'Guam',  'Guam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '320','320',  'GTM',  'GT',  'Guatemala',  'Guatemala');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '254','254',  'GUF',  'GF',  'Guayana Francesa',  'Guayana Francesa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '831','831',  'GGY',  'GG',  'Guernsey',  'Guernsey');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '324','324',  'GIN',  'GN',  'Guinea',  'Guinea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '226','226',  'GNQ',  'GQ',  'Guinea Ecuatorial',  'Guinea Ecuatorial');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '624','624',  'GNB',  'GW',  'Guinea-Bissau',  'Guinea-Bissau');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '328','328',  'GUY',  'GY',  'Guyana',  'Guyana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '332','332',  'HTI',  'HT',  'Haití',  'Haití');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '334','334',  'HMD',  'HM',  'Islas Heard y McDonald',  'Islas Heard y McDonald');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '340','340',  'HND',  'HN',  'Honduras',  'Honduras');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '344','344',  'HKG',  'HK',  'Hong Kong',  'Hong Kong');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '348','348',  'HUN',  'HU',  'Hungría',  'Hungría');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '356','356',  'IND',  'IN',  'India',  'India');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '360','360',  'IDN',  'ID',  'Indonesia',  'Indonesia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '364','364',  'IRN',  'IR',  'Irán',  'Irán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '368','368',  'IRQ',  'IQ',  'Iraq',  'Iraq');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '372','372',  'IRL',  'IE',  'Irlanda',  'Irlanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '352','352',  'ISL',  'IS',  'Islandia',  'Islandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '376','376',  'ISR',  'IL',  'Israel',  'Israel');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '380','380',  'ITA',  'IT',  'Italia',  'Italia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '388','388',  'JAM',  'JM',  'Jamaica',  'Jamaica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '392','392',  'JPN',  'JP',  'Japón',  'Japón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '832','832',  'JEY',  'JE',  'Jersey',  'Jersey');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '400','400',  'JOR',  'JO',  'Jordania',  'Jordania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '398','398',  'KAZ',  'KZ',  'Kazajistán',  'Kazajistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '404','404',  'KEN',  'KE',  'Kenia',  'Kenia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '417','417',  'KGZ',  'KG',  'Kirguistán',  'Kirguistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '296','296',  'KIR',  'KI',  'Kiribati',  'Kiribati');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '414','414',  'KWT',  'KW',  'Kuwait',  'Kuwait');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '418','418',  'LAO',  'LA',  'Laos',  'Laos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '426','426',  'LSO',  'LS',  'Lesoto',  'Lesoto');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '428','428',  'LVA',  'LV',  'Letonia',  'Letonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '422','422',  'LBN',  'LB',  'Líbano',  'Líbano');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '430','430',  'LBR',  'LR',  'Liberia',  'Liberia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '434','434',  'LBY',  'LY',  'Libia',  'Libia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '438','438',  'LIE',  'LI',  'Liechtenstein',  'Liechtenstein');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '440','440',  'LTU',  'LT',  'Lituania',  'Lituania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '442','442',  'LUX',  'LU',  'Luxemburgo',  'Luxemburgo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '446','446',  'MAC',  'MO',  'Macao',  'Macao');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '807','807',  'MKD',  'MK',  'ARY Macedonia',  'ARY Macedonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '450','450',  'MDG',  'MG',  'Madagascar',  'Madagascar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '458','458',  'MYS',  'MY',  'Malasia',  'Malasia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '454','454',  'MWI',  'MW',  'Malawi',  'Malawi');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '462','462',  'MDV',  'MV',  'Maldivas',  'Maldivas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '466','466',  'MLI',  'ML',  'Malí',  'Malí');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '470','470',  'MLT',  'MT',  'Malta',  'Malta');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '238','238',  'FLK',  'FK',  'Islas Malvinas',  'Islas Malvinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '833','833',  'IMN',  'IM',  'Isla de Man',  'Isla de Man');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '580','580',  'MNP',  'MP',  'Islas Marianas del Norte',  'Islas Marianas del Norte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '504','504',  'MAR',  'MA',  'Marruecos',  'Marruecos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '584','584',  'MHL',  'MH',  'Islas Marshall',  'Islas Marshall');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '474','474',  'MTQ',  'MQ',  'Martinica',  'Martinica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '480','480',  'MUS',  'MU',  'Mauricio',  'Mauricio');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '478','478',  'MRT',  'MR',  'Mauritania',  'Mauritania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '175','175',  'MYT',  'YT',  'Mayotte',  'Mayotte');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '484','484',  'MEX',  'MX',  'México',  'México');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '583','583',  'FSM',  'FM',  'Micronesia',  'Micronesia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '498','498',  'MDA',  'MD',  'Moldavia',  'Moldavia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '492','492',  'MCO',  'MC',  'Mónaco',  'Mónaco');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '496','496',  'MNG',  'MN',  'Mongolia',  'Mongolia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '499','499',  'MNE',  'ME',  'Montenegro',  'Montenegro');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '500','500',  'MSR',  'MS',  'Montserrat',  'Montserrat');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '508','508',  'MOZ',  'MZ',  'Mozambique',  'Mozambique');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '104','104',  'MMR',  'MM',  'Birmania',  'Birmania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '516','516',  'NAM',  'NA',  'Namibia',  'Namibia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '520','520',  'NRU',  'NR',  'Nauru',  'Nauru');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '162','162',  'CXR',  'CX',  'Isla de Navidad',  'Isla de Navidad');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '524','524',  'NPL',  'NP',  'Nepal',  'Nepal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '558','558',  'NIC',  'NI',  'Nicaragua',  'Nicaragua');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '562','562',  'NER',  'NE',  'Níger',  'Níger');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '566','566',  'NGA',  'NG',  'Nigeria',  'Nigeria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '570','570',  'NIU',  'NU',  'Niue',  'Niue');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '574','574',  'NFK',  'NF',  'Norfolk',  'Norfolk');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '578','578',  'NOR',  'NO',  'Noruega',  'Noruega');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '540','540',  'NCL',  'NC',  'Nueva Caledonia',  'Nueva Caledonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '554','554',  'NZL',  'NZ',  'Nueva Zelanda',  'Nueva Zelanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '512','512',  'OMN',  'OM',  'Omán',  'Omán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '528','528',  'NLD',  'NL',  'Países Bajos',  'Países Bajos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '586','586',  'PAK',  'PK',  'Pakistán',  'Pakistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '585','585',  'PLW',  'PW',  'Palaos',  'Palaos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '275','275',  'PSE',  'PS',  'Territorios palestinos',  'Territorios palestinos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '591','591',  'PAN',  'PA',  'Panamá',  'Panamá');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '598','598',  'PNG',  'PG',  'Papúa Nueva Guinea',  'Papúa Nueva Guinea');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '600','600',  'PRY',  'PY',  'Paraguay',  'Paraguay');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '604','604',  'PER',  'PE',  'Perú',  'Perú');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '612','612',  'PCN',  'PN',  'Islas Pitcairn',  'Islas Pitcairn');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '258','258',  'PYF',  'PF',  'Polinesia Francesa',  'Polinesia Francesa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '616','616',  'POL',  'PL',  'Polonia',  'Polonia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '620','620',  'PRT',  'PT',  'Portugal',  'Portugal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '630','630',  'PRI',  'PR',  'Puerto Rico',  'Puerto Rico');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '634','634',  'QAT',  'QA',  'Qatar',  'Qatar');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '826','826',  'GBR',  'GB',  'Reino Unido',  'Reino Unido');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '638','638',  'REU',  'RE',  'Reunión',  'Reunión');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '646','646',  'RWA',  'RW',  'Ruanda',  'Ruanda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '642','642',  'ROU',  'RO',  'Rumania',  'Rumania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '643','643',  'RUS',  'RU',  'Rusia',  'Rusia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '732','732',  'ESH',  'EH',  'Sahara Occidental',  'Sahara Occidental');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '090','090',  'SLB',  'SB',  'Islas Salomón',  'Islas Salomón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '882','882',  'WSM',  'WS',  'Samoa',  'Samoa');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '016','016',  'ASM',  'AS',  'Americana Samoa Americana',  'Americana Samoa Americana');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '659','659',  'KNA',  'KN',  'San Cristóbal y Nieves',  'San Cristóbal y Nieves');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '674','674',  'SMR',  'SM',  'San Marino',  'San Marino');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '666','666',  'SPM',  'PM',  'San Pedro y Miquelón',  'San Pedro y Miquelón');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '670','670',  'VCT',  'VC',  'San Vicente y lasGranadinas',  'San Vicente y lasGranadinas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '654','654',  'SHN',  'SH',  'Santa Helena',  'Santa Helena');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '662','662',  'LCA',  'LC',  'Santa Lucía',  'Santa Lucía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '678','678',  'STP',  'ST',  'Santo Tomé y Príncipe',  'Santo Tomé y Príncipe');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '686','686',  'SEN',  'SN',  'Senegal',  'Senegal');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '688','688',  'SRB',  'RS',  'Serbia',  'Serbia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '690','690',  'SYC',  'SC',  'Seychelles',  'Seychelles');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '694','694',  'SLE',  'SL',  'Sierra Leona',  'Sierra Leona');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '702','702',  'SGP',  'SG',  'Singapur',  'Singapur');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '760','760',  'SYR',  'SY',  'Siria',  'Siria');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '706','706',  'SOM',  'SO',  'Somalia',  'Somalia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '144','144',  'LKA',  'LK',  'Sri Lanka',  'Sri Lanka');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '748','748',  'SWZ',  'SZ',  'Suazilandia',  'Suazilandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '710','710',  'ZAF',  'ZA',  'Sudáfrica',  'Sudáfrica');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '736','736',  'SDN',  'SD',  'Sudán',  'Sudán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '752','752',  'SWE',  'SE',  'Suecia',  'Suecia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '756','756',  'CHE',  'CH',  'Suiza',  'Suiza');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '740','740',  'SUR',  'SR',  'Surinam',  'Surinam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '744','744',  'SJM',  'SJ',  'Svalbard y Jan Mayen',  'Svalbard y Jan Mayen');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '764','764',  'THA',  'TH',  'Tailandia',  'Tailandia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '158','158',  'TWN',  'TW',  'República de China',  'República de China');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '834','834',  'TZA',  'TZ',  'Tanzania',  'Tanzania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '762','762',  'TJK',  'TJ',  'Tayikistán',  'Tayikistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '086','086',  'IOT',  'IO',  'Territorio Británico del OcéanoÍndico',  'Territorio Británico del Océano Índico');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '260','260',  'ATF',  'TF',  'Territorios Australes Franceses',  'Territorios Australes Franceses');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '626','626',  'TLS',  'TL',  'Timor Oriental',  'Timor Oriental');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '768','768',  'TGO',  'TG',  'Togo',  'Togo');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '772','772',  'TKL',  'TK',  'Tokelau',  'Tokelau');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '776','776',  'TON',  'TO',  'Tonga',  'Tonga');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '780','780',  'TTO',  'TT',  'Trinidad y Tobago',  'Trinidad y Tobago');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '788','788',  'TUN',  'TN',  'Túnez',  'Túnez');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '796','796',  'TCA',  'TC',  'Islas Turcas y Caicos',  'Islas Turcas y Caicos');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '795','795',  'TKM',  'TM',  'Turkmenistán',  'Turkmenistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '792','792',  'TUR',  'TR',  'Turquía',  'Turquía');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '798','798',  'TUV',  'TV',  'Tuvalu',  'Tuvalu');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '804','804',  'UKR',  'UA',  'Ucrania',  'Ucrania');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '800','800',  'UGA',  'UG',  'Uganda',  'Uganda');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '858','858',  'URY',  'UY',  'Uruguay',  'Uruguay');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '860','860',  'UZB',  'UZ',  'Uzbekistán',  'Uzbekistán');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '548','548',  'VUT',  'VU',  'Vanuatu',  'Vanuatu');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '336','336',  'VAT',  'VA',  'Ciudad del Vaticano',  'Ciudad del Vaticano');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '862','862',  'VEN',  'VE',  'Venezuela',  'Venezuela');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '704','704',  'VNM',  'VN',  'Vietnam',  'Vietnam');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '092','092',  'VGB',  'VG',  'Islas Vírgenes Británicas',  'Islas Vírgenes Británicas');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '850','850',  'VIR',  'VI',  'Islas Vírgenes Estadounidenses',  'Islas Vírgenes Estadounidenses');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '876','876',  'WLF',  'WF',  'Wallis y Futuna',  'Wallis y Futuna');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '887','887',  'YEM',  'YE',  'Yemen',  'Yemen');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '262','262',  'DJI',  'DJ',  'Yibuti',  'Yibuti');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '894','894',  'ZMB',  'ZM',  'Zambia',  'Zambia');
INSERT INTO pais (id, cod_num, alfa_tres, alfa_dos, nombre, nacionalidad) VALUES ( '716','716',  'ZWE',  'ZW',  'Zimbabue',  'Zimbabue');

--Regiones

INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('01','Región de Arica y Parinacota','Norte Grande','XV','15',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('02','Región de Tarapacá','Norte Grande','I','1',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('03','Región de Antofagasta','Norte Grande','II','2',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('04','Región de Atacama','Norte Chico','III','3',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('05','Región de Coquimbo','Norte Chico','IV','4',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('06','Región de Valparaíso','Núcleo Central','V','5',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('07','Región del Libertador General Bernardo O''Higgins','Núcleo Central','VI','6',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('08','Región del Maule','Núcleo Central','VII','7',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('09','Región del Biobío','Concepción y La Frontera','VIII','8',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('10','Región de la Araucanía','Concepción y La Frontera','IX','9',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('11','Región de los Ríos','Región de los Lagos','XIV','14',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('12','Región de Los Lagos','Región de los Lagos','X','10',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('13','Región de Aisén del General Carlos Ibáñez del Campo','Región de los Canales','XI','11',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('14','Región de Magallanes y de la Antártica Chilena','Región de los Canales','XII','12',152);
INSERT INTO region (id,nombre,corfo,codigo,numero,id_pais) VALUES ('15','Región Metropolitana de Santiago','Núcleo Central','RM','13',152);

--Provincias
INSERT INTO provincia (id,nombre,id_region) VALUES (01,'Arica',(SELECT id FROM region WHERE nombre='Región de Arica y Parinacota'));
INSERT INTO provincia (id,nombre,id_region) VALUES (02,'Parinacota',(SELECT id FROM region WHERE nombre='Región de Arica y Parinacota'));
INSERT INTO provincia (id,nombre,id_region) VALUES (03,'El Tamarugal',(SELECT id FROM region WHERE nombre='Región de Tarapacá'));
INSERT INTO provincia (id,nombre,id_region) VALUES (04,'Iquique',(SELECT id FROM region WHERE nombre='Región de Tarapacá'));
INSERT INTO provincia (id,nombre,id_region) VALUES (05,'Tocopilla',(SELECT id FROM region WHERE nombre='Región de Antofagasta'));
INSERT INTO provincia (id,nombre,id_region) VALUES (06,'El Loa',(SELECT id FROM region WHERE nombre='Región de Antofagasta'));
INSERT INTO provincia (id,nombre,id_region) VALUES (07,'Antofagasta',(SELECT id FROM region WHERE nombre='Región de Antofagasta'));
INSERT INTO provincia (id,nombre,id_region) VALUES (08,'Chañaral',(SELECT id FROM region WHERE nombre='Región de Atacama'));
INSERT INTO provincia (id,nombre,id_region) VALUES (09,'Copiapó',(SELECT id FROM region WHERE nombre='Región de Atacama'));
INSERT INTO provincia (id,nombre,id_region) VALUES (10,'Huasco',(SELECT id FROM region WHERE nombre='Región de Atacama'));
INSERT INTO provincia (id,nombre,id_region) VALUES (11,'Elqui',(SELECT id FROM region WHERE nombre='Región de Coquimbo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (12,'Limarí',(SELECT id FROM region WHERE nombre='Región de Coquimbo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (13,'Choapa',(SELECT id FROM region WHERE nombre='Región de Coquimbo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (14,'Petorca',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (15,'Los Andes',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (16,'San Felipe de Aconcagua',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (17,'Quillota',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (18,'Valparaíso',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (19,'San Antonio',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (20,'Isla de Pascua',(SELECT id FROM region WHERE nombre='Región de Valparaíso'));
INSERT INTO provincia (id,nombre,id_region) VALUES (21,'Cachapoal',(SELECT id FROM region WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincia (id,nombre,id_region) VALUES (22,'Colchagua',(SELECT id FROM region WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincia (id,nombre,id_region) VALUES (23,'Cardenal Caro',(SELECT id FROM region WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincia (id,nombre,id_region) VALUES (24,'Curicó',(SELECT id FROM region WHERE nombre='Región del Maule'));
INSERT INTO provincia (id,nombre,id_region) VALUES (25,'Talca',(SELECT id FROM region WHERE nombre='Región del Maule'));
INSERT INTO provincia (id,nombre,id_region) VALUES (26,'Linares',(SELECT id FROM region WHERE nombre='Región del Maule'));
INSERT INTO provincia (id,nombre,id_region) VALUES (27,'Cauquenes',(SELECT id FROM region WHERE nombre='Región del Maule'));
INSERT INTO provincia (id,nombre,id_region) VALUES (28,'Ñuble',(SELECT id FROM region WHERE nombre='Región del Biobío'));
INSERT INTO provincia (id,nombre,id_region) VALUES (29,'Biobío',(SELECT id FROM region WHERE nombre='Región del Biobío'));
INSERT INTO provincia (id,nombre,id_region) VALUES (30,'Concepción',(SELECT id FROM region WHERE nombre='Región del Biobío'));
INSERT INTO provincia (id,nombre,id_region) VALUES (31,'Arauco',(SELECT id FROM region WHERE nombre='Región del Biobío'));
INSERT INTO provincia (id,nombre,id_region) VALUES (32,'Malleco',(SELECT id FROM region WHERE nombre='Región de la Araucanía'));
INSERT INTO provincia (id,nombre,id_region) VALUES (33,'Cautín',(SELECT id FROM region WHERE nombre='Región de la Araucanía'));
INSERT INTO provincia (id,nombre,id_region) VALUES (34,'Valdivia',(SELECT id FROM region WHERE nombre='Región de los Ríos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (35,'Ranco',(SELECT id FROM region WHERE nombre='Región de los Ríos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (36,'Osorno',(SELECT id FROM region WHERE nombre='Región de Los Lagos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (37,'Llanquihue',(SELECT id FROM region WHERE nombre='Región de Los Lagos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (38,'Chiloé',(SELECT id FROM region WHERE nombre='Región de Los Lagos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (39,'Palena',(SELECT id FROM region WHERE nombre='Región de Los Lagos'));
INSERT INTO provincia (id,nombre,id_region) VALUES (40,'Coihaique',(SELECT id FROM region WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (41,'Aisén',(SELECT id FROM region WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (42,'General Carrera',(SELECT id FROM region WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (43,'Capitán Prat',(SELECT id FROM region WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincia (id,nombre,id_region) VALUES (44,'Última Esperanza',(SELECT id FROM region WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincia (id,nombre,id_region) VALUES (45,'Magallanes',(SELECT id FROM region WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincia (id,nombre,id_region) VALUES (46,'Tierra del Fuego',(SELECT id FROM region WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincia (id,nombre,id_region) VALUES (47,'Antártica Chilena',(SELECT id FROM region WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincia (id,nombre,id_region) VALUES (48,'Chacabuco',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincia (id,nombre,id_region) VALUES (49,'Cordillera',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincia (id,nombre,id_region) VALUES (50,'Maipo',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincia (id,nombre,id_region) VALUES (51,'Talagante',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincia (id,nombre,id_region) VALUES (52,'Melipilla',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincia (id,nombre,id_region) VALUES (53,'Santiago',(SELECT id FROM region WHERE nombre='Región Metropolitana de Santiago'));

--Comunas


INSERT INTO comuna (id,nombre,id_provincia) VALUES (1,'Arica',(SELECT id FROM provincia WHERE nombre='Arica'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (2,'Camarones',(SELECT id FROM provincia WHERE nombre='Arica'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (3,'General Lagos',(SELECT id FROM provincia WHERE nombre='Parinacota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (4,'Putre',(SELECT id FROM provincia WHERE nombre='Parinacota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (5,'Camiña',(SELECT id FROM provincia WHERE nombre='El Tamarugal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (6,'Colchane',(SELECT id FROM provincia WHERE nombre='El Tamarugal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (7,'Huara',(SELECT id FROM provincia WHERE nombre='El Tamarugal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (8,'Pica',(SELECT id FROM provincia WHERE nombre='El Tamarugal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (9,'Pozo Almonte',(SELECT id FROM provincia WHERE nombre='El Tamarugal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (10,'Iquique',(SELECT id FROM provincia WHERE nombre='Iquique'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (11,'Alto Hospicio',(SELECT id FROM provincia WHERE nombre='Iquique'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (12,'María Elena',(SELECT id FROM provincia WHERE nombre='Tocopilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (13,'Tocopilla',(SELECT id FROM provincia WHERE nombre='Tocopilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (14,'Calama',(SELECT id FROM provincia WHERE nombre='El Loa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (15,'Ollagüe',(SELECT id FROM provincia WHERE nombre='El Loa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (16,'San Pedro de Atacama',(SELECT id FROM provincia WHERE nombre='El Loa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (17,'Antofagasta',(SELECT id FROM provincia WHERE nombre='Antofagasta'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (18,'Mejillones',(SELECT id FROM provincia WHERE nombre='Antofagasta'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (19,'Sierra Gorda',(SELECT id FROM provincia WHERE nombre='Antofagasta'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (20,'Taltal',(SELECT id FROM provincia WHERE nombre='Antofagasta'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (21,'Chañaral',(SELECT id FROM provincia WHERE nombre='Chañaral'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (22,'Diego de Almagro',(SELECT id FROM provincia WHERE nombre='Chañaral'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (23,'Copiapó',(SELECT id FROM provincia WHERE nombre='Copiapó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (24,'Caldera',(SELECT id FROM provincia WHERE nombre='Copiapó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (25,'Tierra Amarilla',(SELECT id FROM provincia WHERE nombre='Copiapó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (26,'Vallenar',(SELECT id FROM provincia WHERE nombre='Huasco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (27,'Freirina',(SELECT id FROM provincia WHERE nombre='Huasco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (28,'Huasco',(SELECT id FROM provincia WHERE nombre='Huasco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (29,'Alto del Carmen',(SELECT id FROM provincia WHERE nombre='Huasco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (30,'Andacollo',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (31,'Coquimbo',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (32,'La Higuera',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (33,'La Serena',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (34,'Paihuano',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (35,'Vicuña',(SELECT id FROM provincia WHERE nombre='Elqui'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (36,'Ovalle',(SELECT id FROM provincia WHERE nombre='Limarí'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (37,'Río Hurtado',(SELECT id FROM provincia WHERE nombre='Limarí'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (38,'Monte Patria',(SELECT id FROM provincia WHERE nombre='Limarí'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (39,'Combarbalá',(SELECT id FROM provincia WHERE nombre='Limarí'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (40,'Punitaqui',(SELECT id FROM provincia WHERE nombre='Limarí'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (41,'Illapel',(SELECT id FROM provincia WHERE nombre='Choapa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (42,'Salamanca',(SELECT id FROM provincia WHERE nombre='Choapa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (43,'Los Vilos',(SELECT id FROM provincia WHERE nombre='Choapa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (44,'Canela',(SELECT id FROM provincia WHERE nombre='Choapa'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (45,'La Ligua',(SELECT id FROM provincia WHERE nombre='Petorca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (46,'Cabildo',(SELECT id FROM provincia WHERE nombre='Petorca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (47,'Zapallar',(SELECT id FROM provincia WHERE nombre='Petorca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (48,'Papudo',(SELECT id FROM provincia WHERE nombre='Petorca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (49,'Petorca',(SELECT id FROM provincia WHERE nombre='Petorca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (50,'Los Andes',(SELECT id FROM provincia WHERE nombre='Los Andes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (51,'San Esteban',(SELECT id FROM provincia WHERE nombre='Los Andes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (52,'Calle Larga',(SELECT id FROM provincia WHERE nombre='Los Andes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (53,'Rinconada',(SELECT id FROM provincia WHERE nombre='Los Andes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (54,'San Felipe',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (55,'Llaillay',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (56,'Putaendo',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (57,'Santa María',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (58,'Catemu',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (59,'Panquehue',(SELECT id FROM provincia WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (60,'Quillota',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (61,'La Calera',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (62,'Limache',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (63,'Nogales',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (64,'Hijuelas',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (65,'Olmué',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (66,'La Cruz',(SELECT id FROM provincia WHERE nombre='Quillota'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (67,'Valparaíso',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (68,'Viña del Mar',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (69,'Quilpué',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (70,'Villa Alemana',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (71,'Concón',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (72,'Quintero',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (73,'Puchuncaví',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (74,'Casablanca',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (75,'Juan Fernández',(SELECT id FROM provincia WHERE nombre='Valparaíso'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (76,'Algarrobo',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (77,'El Quisco',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (78,'El Tabo',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (79,'Cartagena',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (80,'San Antonio',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (81,'Santo Domingo',(SELECT id FROM provincia WHERE nombre='San Antonio'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (82,'Isla de Pascua',(SELECT id FROM provincia WHERE nombre='Isla de Pascua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (83,'Codegua',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (84,'Coínco',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (85,'Coltauco',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (86,'Doñihue',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (87,'Graneros',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (88,'Las Cabras',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (89,'Machalí',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (90,'Malloa',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (91,'Olivar',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (92,'Peumo',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (93,'Pichidegua',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (94,'Quinta de Tilcoco',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (95,'Rancagua',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (96,'Requínoa',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (97,'Rengo',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (98,'Mostazal',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (99,'San Vicente de Tagua Tagua',(SELECT id FROM provincia WHERE nombre='Cachapoal'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (100,'Chépica',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (101,'Chimbarongo',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (102,'Lolol',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (103,'Nancagua',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (104,'Palmilla',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (105,'Peralillo',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (106,'Placilla',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (107,'Pumanque',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (108,'San Fernando',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (109,'Santa Cruz',(SELECT id FROM provincia WHERE nombre='Colchagua'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (110,'La Estrella',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (111,'Litueche',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (112,'Marchigüe',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (113,'Navidad',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (114,'Paredones',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (115,'Pichilemu',(SELECT id FROM provincia WHERE nombre='Cardenal Caro'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (116,'Curicó',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (117,'Hualañé',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (118,'Licantén',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (119,'Molina',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (120,'Rauco',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (121,'Romeral',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (122,'Sagrada Familia',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (123,'Teno',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (124,'Vichuquén',(SELECT id FROM provincia WHERE nombre='Curicó'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (125,'Talca',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (126,'San Clemente',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (127,'Pelarco',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (128,'Pencahue',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (129,'Maule',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (130,'San Rafael',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (131,'Curepto',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (132,'Constitución',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (133,'Empedrado',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (134,'Río Claro',(SELECT id FROM provincia WHERE nombre='Talca'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (135,'Linares',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (136,'San Javier de Loncomilla',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (137,'Parral',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (138,'Villa Alegre',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (139,'Longaví',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (140,'Colbún',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (141,'Retiro',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (142,'Yerbas Buenas',(SELECT id FROM provincia WHERE nombre='Linares'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (143,'Cauquenes',(SELECT id FROM provincia WHERE nombre='Cauquenes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (144,'Chanco',(SELECT id FROM provincia WHERE nombre='Cauquenes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (145,'Pelluhue',(SELECT id FROM provincia WHERE nombre='Cauquenes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (146,'Bulnes',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (147,'Chillán',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (148,'Chillán Viejo',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (149,'Cobquecura',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (150,'Coelemu',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (151,'Coihueco',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (152,'El Carmen',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (153,'Ninhue',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (154,'Ñiquén',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (155,'Pemuco',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (156,'Pinto',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (157,'Portezuelo',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (158,'Quillón',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (159,'Quirihue',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (160,'Ránquil',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (161,'San Carlos',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (162,'San Fabián',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (163,'San Ignacio',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (164,'San Nicolás',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (165,'Treguaco',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (166,'Yungay',(SELECT id FROM provincia WHERE nombre='Ñuble'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (167,'Alto Biobío',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (168,'Antuco',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (169,'Cabrero',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (170,'Laja',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (171,'Los Ángeles',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (172,'Mulchén',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (173,'Nacimiento',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (174,'Negrete',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (175,'Quilaco',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (176,'Quilleco',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (177,'San Rosendo',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (178,'Santa Bárbara',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (179,'Tucapel',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (180,'Yumbel',(SELECT id FROM provincia WHERE nombre='Biobío'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (181,'Concepción',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (182,'Coronel',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (183,'Chiguayante',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (184,'Florida',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (185,'Hualpén',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (186,'Hualqui',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (187,'Lota',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (188,'Penco',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (189,'San Pedro de la Paz',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (190,'Santa Juana',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (191,'Talcahuano',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (192,'Tomé',(SELECT id FROM provincia WHERE nombre='Concepción'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (193,'Arauco',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (194,'Cañete',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (195,'Contulmo',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (196,'Curanilahue',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (197,'Lebu',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (198,'Los Álamos',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (199,'Tirúa',(SELECT id FROM provincia WHERE nombre='Arauco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (200,'Angol',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (201,'Collipulli',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (202,'Curacautín',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (203,'Ercilla',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (204,'Lonquimay',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (205,'Los Sauces',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (206,'Lumaco',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (207,'Purén',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (208,'Renaico',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (209,'Traiguén',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (210,'Victoria',(SELECT id FROM provincia WHERE nombre='Malleco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (211,'Temuco',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (212,'Carahue',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (213,'Cholchol',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (214,'Cunco',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (215,'Curarrehue',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (216,'Freire',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (217,'Galvarino',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (218,'Gorbea',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (219,'Lautaro',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (220,'Loncoche',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (221,'Melipeuco',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (222,'Nueva Imperial',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (223,'Padre Las Casas',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (224,'Perquenco',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (225,'Pitrufquén',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (226,'Pucón',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (227,'Saavedra',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (228,'Teodoro Schmidt',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (229,'Toltén',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (230,'Vilcún',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (231,'Villarrica',(SELECT id FROM provincia WHERE nombre='Cautín'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (232,'Valdivia',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (233,'Corral',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (234,'Lanco',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (235,'Los Lagos',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (236,'Mariquina',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (237,'Máfil',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (238,'Paillaco',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (239,'Panguipulli',(SELECT id FROM provincia WHERE nombre='Valdivia'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (240,'La Unión',(SELECT id FROM provincia WHERE nombre='Ranco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (241,'Futrono',(SELECT id FROM provincia WHERE nombre='Ranco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (242,'Lago Ranco',(SELECT id FROM provincia WHERE nombre='Ranco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (243,'Río Bueno',(SELECT id FROM provincia WHERE nombre='Ranco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (244,'Osorno',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (245,'Puerto Octay',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (246,'Purranque',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (247,'Puyehue',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (248,'Río Negro',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (249,'San Pablo',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (250,'San Juan de la Costa',(SELECT id FROM provincia WHERE nombre='Osorno'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (251,'Calbuco',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (252,'Cochamó',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (253,'Fresia',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (254,'Frutillar',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (255,'Llanquihue',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (256,'Los Muermos',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (257,'Maullín',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (258,'Puerto Montt',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (259,'Puerto Varas',(SELECT id FROM provincia WHERE nombre='Llanquihue'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (260,'Ancud',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (261,'Castro',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (262,'Chonchi',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (263,'Curaco de Vélez',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (264,'Dalcahue',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (265,'Puqueldón',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (266,'Queilén',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (267,'Quellón',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (268,'Quemchi',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (269,'Quinchao',(SELECT id FROM provincia WHERE nombre='Chiloé'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (270,'Chaitén',(SELECT id FROM provincia WHERE nombre='Palena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (271,'Futaleufú',(SELECT id FROM provincia WHERE nombre='Palena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (272,'Hualaihué',(SELECT id FROM provincia WHERE nombre='Palena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (273,'Palena',(SELECT id FROM provincia WHERE nombre='Palena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (274,'Coihaique',(SELECT id FROM provincia WHERE nombre='Coihaique'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (275,'Lago Verde',(SELECT id FROM provincia WHERE nombre='Coihaique'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (276,'Aisén',(SELECT id FROM provincia WHERE nombre='Aisén'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (277,'Cisnes',(SELECT id FROM provincia WHERE nombre='Aisén'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (278,'Guaitecas',(SELECT id FROM provincia WHERE nombre='Aisén'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (279,'Chile Chico',(SELECT id FROM provincia WHERE nombre='General Carrera'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (280,'Río Ibáñez',(SELECT id FROM provincia WHERE nombre='General Carrera'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (281,'Cochrane',(SELECT id FROM provincia WHERE nombre='Capitán Prat'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (282,'O''Higgins',(SELECT id FROM provincia WHERE nombre='Capitán Prat'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (283,'Tortel',(SELECT id FROM provincia WHERE nombre='Capitán Prat'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (284,'Natales',(SELECT id FROM provincia WHERE nombre='Última Esperanza'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (285,'Torres del Paine',(SELECT id FROM provincia WHERE nombre='Última Esperanza'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (286,'Laguna Blanca',(SELECT id FROM provincia WHERE nombre='Magallanes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (287,'Punta Arenas',(SELECT id FROM provincia WHERE nombre='Magallanes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (288,'Río Verde',(SELECT id FROM provincia WHERE nombre='Magallanes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (289,'San Gregorio',(SELECT id FROM provincia WHERE nombre='Magallanes'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (290,'Porvenir',(SELECT id FROM provincia WHERE nombre='Tierra del Fuego'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (291,'Primavera',(SELECT id FROM provincia WHERE nombre='Tierra del Fuego'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (292,'Timaukel',(SELECT id FROM provincia WHERE nombre='Tierra del Fuego'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (293,'Cabo de Hornos',(SELECT id FROM provincia WHERE nombre='Antártica Chilena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (294,'Antártica',(SELECT id FROM provincia WHERE nombre='Antártica Chilena'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (295,'Colina',(SELECT id FROM provincia WHERE nombre='Chacabuco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (296,'Lampa',(SELECT id FROM provincia WHERE nombre='Chacabuco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (297,'Tiltil',(SELECT id FROM provincia WHERE nombre='Chacabuco'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (298,'Puente Alto',(SELECT id FROM provincia WHERE nombre='Cordillera'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (299,'San José de Maipo',(SELECT id FROM provincia WHERE nombre='Cordillera'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (300,'Pirque',(SELECT id FROM provincia WHERE nombre='Cordillera'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (301,'San Bernardo',(SELECT id FROM provincia WHERE nombre='Maipo'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (302,'Buin',(SELECT id FROM provincia WHERE nombre='Maipo'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (303,'Paine',(SELECT id FROM provincia WHERE nombre='Maipo'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (304,'Calera de Tango',(SELECT id FROM provincia WHERE nombre='Maipo'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (305,'Isla de Maipo',(SELECT id FROM provincia WHERE nombre='Talagante'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (306,'El Monte',(SELECT id FROM provincia WHERE nombre='Talagante'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (307,'Padre Hurtado',(SELECT id FROM provincia WHERE nombre='Talagante'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (308,'Peñaflor',(SELECT id FROM provincia WHERE nombre='Talagante'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (309,'Talagante',(SELECT id FROM provincia WHERE nombre='Talagante'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (310,'Curacaví',(SELECT id FROM provincia WHERE nombre='Melipilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (311,'María Pinto',(SELECT id FROM provincia WHERE nombre='Melipilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (312,'Melipilla',(SELECT id FROM provincia WHERE nombre='Melipilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (313,'San Pedro',(SELECT id FROM provincia WHERE nombre='Melipilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (314,'Alhué',(SELECT id FROM provincia WHERE nombre='Melipilla'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (315,'Cerrillos',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (316,'Cerro Navia',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (317,'Conchalí',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (318,'El Bosque',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (319,'Estación Central',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (320,'Huechuraba',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (321,'Independencia',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (322,'La Cisterna',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (323,'La Granja',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (324,'La Florida',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (325,'La Pintana',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (326,'La Reina',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (327,'Las Condes',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (328,'Lo Barnechea',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (329,'Lo Espejo',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (330,'Lo Prado',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (331,'Macul',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (332,'Maipú',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (333,'Ñuñoa',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (334,'Pedro Aguirre Cerda',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (335,'Peñalolén',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (336,'Providencia',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (337,'Pudahuel',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (338,'Quilicura',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (339,'Quinta Normal',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (340,'Recoleta',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (341,'Renca',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (342,'San Miguel',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (343,'San Joaquín',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (344,'San Ramón',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (345,'Santiago',(SELECT id FROM provincia WHERE nombre='Santiago'));
INSERT INTO comuna (id,nombre,id_provincia) VALUES (346,'Vitacura',(SELECT id FROM provincia WHERE nombre='Santiago'));
